In [11]:
import os

import anndata
import pandas as pd
import scanpy as sc
sc.logging.print_versions()

scanpy==1.4.6.dev9+ge632939 anndata==0.7rc1 umap==0.3.10 numpy==1.17.3 scipy==1.3.2 pandas==0.25.3 scikit-learn==0.23.2 statsmodels==0.12.1 python-igraph==0.7.1 louvain==0.6.1

## def describe

In [2]:
def describe(df, random=False):
    print(df.shape)
    print("--- First 5 entries ---")
    display(df.head())
    if random:
        print('--- Random subset ---')
        display(df.sample(5))

In [5]:
mouse1_counts = pd.read_csv('/home/olga/data_lg/data_sm_copy/tabula-microcebus/rawdata/gene_count_tables/Mouse_1_Blood_10X_rawdata.csv', index_col=0).T
describe(mouse1_counts)

(5493, 23433)
--- First 5 entries ---

,XKR4,RP1,SOX17,MRPL15,LYPLA1,TCEA1,RGS20,ATP6V1H,OPRK1,NPBWR1,...,ERCC-00163,ERCC-00164,ERCC-00165,ERCC-00168,ERCC-00170,ERCC-00171,GFP_TRANSGENE,CRE_TRANSGENE,TDTOM_TRANSGENE,ZSGREEN_TRANSGENE
Mouse_Blood_1_10X_AAACCTGAGAGACGAA,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGAGTATGACA,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGCACACGCTG,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGCAGCGATCC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGGTAAGGATT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
mouse1_metadata = pd.read_csv('/home/olga/data_lg/data_sm_copy/tabula-microcebus/rawdata/gene_count_tables/Mouse_1_Blood_10X_annotations_metadata.csv', 
                              index_col=0)
describe(mouse1_metadata)

(5493, 13)
--- First 5 entries ---

,nGene,nUMI,orig.ident,channel,tissue,region,individual,species,method,processed,percent.ribo,free_annotation,compartment
Mouse_Blood_1_10X_AAACCTGAGAGACGAA,1178,2555,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.147162,natural killer cell,lymphoid
Mouse_Blood_1_10X_AAACCTGAGTATGACA,2567,11699,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.373194,B cell (ZBTB32+),lymphoid
Mouse_Blood_1_10X_AAACCTGCACACGCTG,1930,5602,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.159407,classical monocyte,myeloid
Mouse_Blood_1_10X_AAACCTGCAGCGATCC,156,2616,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.005734,removed,NaN
Mouse_Blood_1_10X_AAACCTGGTAAGGATT,2047,6250,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.160000,classical monocyte,myeloid

In [7]:
mouse2_counts = pd.read_csv('/home/olga/data_lg/data_sm_copy/tabula-microcebus/rawdata/gene_count_tables/Mouse_2_Blood_10X_rawdata.csv', index_col=0).T
describe(mouse2_counts)

(10496, 23433)
--- First 5 entries ---

,XKR4,RP1,SOX17,MRPL15,LYPLA1,TCEA1,RGS20,ATP6V1H,OPRK1,NPBWR1,...,ERCC-00163,ERCC-00164,ERCC-00165,ERCC-00168,ERCC-00170,ERCC-00171,GFP_TRANSGENE,CRE_TRANSGENE,TDTOM_TRANSGENE,ZSGREEN_TRANSGENE
Mouse_Blood_2_10X_AAACCTGAGACAAGCC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_2_10X_AAACCTGAGATATGGT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_2_10X_AAACCTGAGGAGCGAG,0,0,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_2_10X_AAACCTGAGGATTCGG,0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_2_10X_AAACCTGAGTACGCCC,0,0,0,0,1,3,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
mouse2_metadata = pd.read_csv('/home/olga/data_lg/data_sm_copy/tabula-microcebus/rawdata/gene_count_tables/Mouse_2_Blood_10X_annotations_metadata.csv', 
                              index_col=0)
describe(mouse2_metadata)

(10496, 13)
--- First 5 entries ---

,nGene,nUMI,orig.ident,channel,tissue,region,individual,species,method,processed,percent.ribo,free_annotation,compartment
Mouse_Blood_2_10X_AAACCTGAGACAAGCC,154,3674,Mouse,Mouse_Blood_2_10X,Blood,NaN,Mouse_2,Mouse,10X,Biohub,0.005716,removed,NaN
Mouse_Blood_2_10X_AAACCTGAGATATGGT,493,1585,Mouse,Mouse_Blood_2_10X,Blood,NaN,Mouse_2,Mouse,10X,Biohub,0.028391,removed,NaN
Mouse_Blood_2_10X_AAACCTGAGGAGCGAG,2199,8071,Mouse,Mouse_Blood_2_10X,Blood,NaN,Mouse_2,Mouse,10X,Biohub,0.211002,classical monocyte,myeloid
Mouse_Blood_2_10X_AAACCTGAGGATTCGG,2316,8051,Mouse,Mouse_Blood_2_10X,Blood,NaN,Mouse_2,Mouse,10X,Biohub,0.146938,classical monocyte,myeloid
Mouse_Blood_2_10X_AAACCTGAGTACGCCC,2807,9819,Mouse,Mouse_Blood_2_10X,Blood,NaN,Mouse_2,Mouse,10X,Biohub,0.216417,classical monocyte,myeloid

## Concatenate counts

In [10]:

counts = pd.concat([mouse1_counts, mouse2_counts])
describe(counts)

(15989, 23433)
--- First 5 entries ---

,XKR4,RP1,SOX17,MRPL15,LYPLA1,TCEA1,RGS20,ATP6V1H,OPRK1,NPBWR1,...,ERCC-00163,ERCC-00164,ERCC-00165,ERCC-00168,ERCC-00170,ERCC-00171,GFP_TRANSGENE,CRE_TRANSGENE,TDTOM_TRANSGENE,ZSGREEN_TRANSGENE
Mouse_Blood_1_10X_AAACCTGAGAGACGAA,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGAGTATGACA,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGCACACGCTG,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGCAGCGATCC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGGTAAGGATT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
is_transgene = counts.columns.map(lambda x: x.endswith('TRANSGENE') or x.startswith('ERCC-')).values
sum(is_transgene)

#

96

In [23]:
def check_is_transgene(x):
    if x.startswith('ERCC-'):
        return True
    elif x.endswith('TRANSGENE'):
        return True
    else:
        return False

In [25]:
non_transgenes = [x for x in counts.columns if not check_is_transgene(x)]

In [27]:
len(non_transgenes)

23337

In [28]:
counts_no_transgenes = counts.loc[:, non_transgenes]
counts_no_transgenes

,XKR4,RP1,SOX17,MRPL15,LYPLA1,TCEA1,RGS20,ATP6V1H,OPRK1,NPBWR1,...,LOC100040031,LOC382133,LOC100040786,SLY,MGC107098,LOC100039810,LOC100041256,LOC100039574,LOC100040911,ERDR1
Mouse_Blood_1_10X_AAACCTGAGAGACGAA,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGAGTATGACA,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
Mouse_Blood_1_10X_AAACCTGCACACGCTG,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Mouse_Blood_1_10X_AAACCTGCAGCGATCC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGGTAAGGATT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mouse_Blood_2_10X_TTTGTCAGTGTCGCTG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_2_10X_TTTGTCAGTTGAACTC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_2_10X_TTTGTCATCCGCGGTA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_2_10X_TTTGTCATCCTAAGTG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_2_10X_TTTGTCATCGAGAGCA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Make columns capitalized, not all caps

In [29]:
counts_no_transgenes.columns = counts_no_transgenes.columns.str.capitalize()
counts_no_transgenes.head()

,Xkr4,Rp1,Sox17,Mrpl15,Lypla1,Tcea1,Rgs20,Atp6v1h,Oprk1,Npbwr1,...,Loc100040031,Loc382133,Loc100040786,Sly,Mgc107098,Loc100039810,Loc100041256,Loc100039574,Loc100040911,Erdr1
Mouse_Blood_1_10X_AAACCTGAGAGACGAA,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGAGTATGACA,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
Mouse_Blood_1_10X_AAACCTGCACACGCTG,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Mouse_Blood_1_10X_AAACCTGCAGCGATCC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mouse_Blood_1_10X_AAACCTGGTAAGGATT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

## Concatenate metadata

In [9]:
metadata = pd.concat([mouse1_metadata, mouse2_metadata])
describe(metadata)

(15989, 13)
--- First 5 entries ---

,nGene,nUMI,orig.ident,channel,tissue,region,individual,species,method,processed,percent.ribo,free_annotation,compartment
Mouse_Blood_1_10X_AAACCTGAGAGACGAA,1178,2555,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.147162,natural killer cell,lymphoid
Mouse_Blood_1_10X_AAACCTGAGTATGACA,2567,11699,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.373194,B cell (ZBTB32+),lymphoid
Mouse_Blood_1_10X_AAACCTGCACACGCTG,1930,5602,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.159407,classical monocyte,myeloid
Mouse_Blood_1_10X_AAACCTGCAGCGATCC,156,2616,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.005734,removed,NaN
Mouse_Blood_1_10X_AAACCTGGTAAGGATT,2047,6250,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.160000,classical monocyte,myeloid

# Add unified annotations

In [30]:
import unified_annotations

blood_grouping = unified_annotations.get_celltype_converter(
    "Blood", ("Mouse", "CE independent dataset", "free_annotation")
) 
blood_grouping = blood_grouping.drop('tissue', axis=1)
print(blood_grouping.shape)
blood_grouping.head()

(37, 3)

,narrow_group,broad_group,compartment_group
"(Mouse, CE independent dataset, free_annotation)",,,
B cell,B cell,B cell,lymphoid
B cell (ZBTB32+),B cell,B cell,lymphoid
CD4+ effector and memory T cell,CD4+ T cell,T cell,lymphoid
CD4+ naive T cell,CD4+ T cell,T cell,lymphoid
CD8+ effector and memory T cell,CD8+ T cell,T cell,lymphoid

In [32]:
metadata_unified = metadata.merge(
    blood_grouping, left_on="free_annotation", right_index=True
)
describe(metadata_unified)

(15989, 16)
--- First 5 entries ---

,nGene,nUMI,orig.ident,channel,tissue,region,individual,species,method,processed,percent.ribo,free_annotation,compartment,narrow_group,broad_group,compartment_group
Mouse_Blood_1_10X_AAACCTGAGAGACGAA,1178,2555,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.147162,natural killer cell,lymphoid,natural killer cell,natural killer cell,lymphoid
Mouse_Blood_1_10X_AAAGTAGAGTTAGGTA,1186,2478,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.179580,natural killer cell,lymphoid,natural killer cell,natural killer cell,lymphoid
Mouse_Blood_1_10X_AAATGCCCATAACCTG,1459,3197,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.174539,natural killer cell,lymphoid,natural killer cell,natural killer cell,lymphoid
Mouse_Blood_1_10X_AAATGCCTCAGTGCAT,1602,4222,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.221933,natural killer cell,lymphoid,natural killer cell,natural killer cell,lymphoid
Mouse_Blood_1_10X_AACCATGCAGCTGCAC,1212,2479,Mouse,Mouse_Blood_1_10X,Blood,NaN,Mouse_1,Mouse,10X,Biohub,0.148447,natural killer cell,lymphoid,natural killer cell,natural killer cell,lymphoid

In [33]:
sorted(metadata_unified.columns)

['broad_group',
 'channel',
 'compartment',
 'compartment_group',
 'free_annotation',
 'individual',
 'method',
 'nGene',
 'nUMI',
 'narrow_group',
 'orig.ident',
 'percent.ribo',
 'processed',
 'region',
 'species',
 'tissue']

## Add individual_v2 column

In [42]:
dict.fromkeys(metadata_unified.individual.unique())

{'Mouse_1': None, 'Mouse_2': None}

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [45]:
indidivual_renamer = {"Mouse_1": "mouse_24_ce1", "Mouse_2": "mouse_25_ce2"}
metadata_unified["individual_v2"] = metadata_unified.individual.map(indidivual_renamer)
metadata_unified["individual_v2"].value_counts()

mouse_25_ce2    10496
mouse_24_ce1     5493
Name: individual_v2, dtype: int64

## Rename metadata columns

In [46]:
metadata_unified_renamed = metadata_unified.rename(
    columns={
        "broad_group": "broad_group",
        "channel": "channel",
        "compartment": None,
        "compartment_group": "compartment_group",
        "free_annotation": "free_annotation",
        "individual": None,
        "individual_v2": "individual",
        "method": None,
        "nGene": "n_genes",
        "nUMI": "n_counts",
        "narrow_group": "narrow_group",
        "orig.ident": None,
        "percent.ribo": None,
        "processed": None,
        "region": None,
        "species": "species",
        "tissue": "tissue",
    }
)
metadata_unified_renamed["species_latin"] = "Mus musculus"
metadata_unified_renamed = metadata_unified_renamed.loc[
    :, metadata_unified_renamed.columns.notnull()
]
print(metadata_unified_renamed.shape)
metadata_unified_renamed.head()

(15989, 11)

,n_genes,n_counts,channel,tissue,species,free_annotation,narrow_group,broad_group,compartment_group,individual,species_latin
Mouse_Blood_1_10X_AAACCTGAGAGACGAA,1178,2555,Mouse_Blood_1_10X,Blood,Mouse,natural killer cell,natural killer cell,natural killer cell,lymphoid,mouse_24_ce1,Mus musculus
Mouse_Blood_1_10X_AAAGTAGAGTTAGGTA,1186,2478,Mouse_Blood_1_10X,Blood,Mouse,natural killer cell,natural killer cell,natural killer cell,lymphoid,mouse_24_ce1,Mus musculus
Mouse_Blood_1_10X_AAATGCCCATAACCTG,1459,3197,Mouse_Blood_1_10X,Blood,Mouse,natural killer cell,natural killer cell,natural killer cell,lymphoid,mouse_24_ce1,Mus musculus
Mouse_Blood_1_10X_AAATGCCTCAGTGCAT,1602,4222,Mouse_Blood_1_10X,Blood,Mouse,natural killer cell,natural killer cell,natural killer cell,lymphoid,mouse_24_ce1,Mus musculus
Mouse_Blood_1_10X_AACCATGCAGCTGCAC,1212,2479,Mouse_Blood_1_10X,Blood,Mouse,natural killer cell,natural killer cell,natural killer cell,lymphoid,mouse_24_ce1,Mus musculus

In [47]:
counts_no_transgenes.shape

(15989, 23337)

In [48]:
adata = anndata.AnnData(X=counts_no_transgenes.loc[metadata_unified_renamed.index], obs=metadata_unified_renamed)
adata

AnnData object with n_obs Ã— n_vars = 15989 Ã— 23337
    obs: 'n_genes', 'n_counts', 'channel', 'tissue', 'species', 'free_annotation', 'narrow_group', 'broad_group', 'compartment_group', 'individual', 'species_latin'

In [49]:
h5ad = '/home/olga/data_lg/data_sm_copy/tabula-microcebus/data-objects/mouse_blood_ce.h5ad'

adata.write(h5ad)

... storing 'channel' as categorical
... storing 'tissue' as categorical
... storing 'species' as categorical
... storing 'free_annotation' as categorical
... storing 'narrow_group' as categorical
... storing 'broad_group' as categorical
... storing 'compartment_group' as categorical
... storing 'individual' as categorical
... storing 'species_latin' as categorical